name: .NET Core

on:
  push:
    branches: [ master,dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Set variables
      id: vars
      run: |
          echo ::set-output name=repo::$(echo ${GITHUB_REPOSITORY})
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo ::set-output name=image-name::$(echo quay.io/neinnovation/policyissue/policyissue-${GITHUB_REF#refs/heads/})
      #- name: npm install and npm run build
       # run: |
        #  npm i
         # npm run build
    - name: Login to Podman
      id: login
      run:  |
         podman login quay.io -u neinnovation -p L/2MYcWU3NInoo3Ekr48t42wg9criQM8gSns1FvawhElopoSzX0HlItR6+zULY3q
    - name: Build Image using Podman
      run: |
         podman build . -t ${{ steps.vars.outputs.repo }}:${{ github.sha }}
    - name: Push Image to Github Registry
      run: |
          podman push ${{ steps.vars.outputs.image-name }}
    - name: Scan Image
      uses: Azure/container-scan@v0
      continue-on-error: true
      with:
        image-name: ${{ steps.vars.outputs.image-name }}:${{ github.sha }}
        username: neinnovation
        password: L/2MYcWU3NInoo3Ekr48t42wg9criQM8gSns1FvawhElopoSzX0HlItR6+zULY3q
        token: ${{ github.token }}
        severity-threshold: HIGH
        run-quality-checks: false
      
